app = "townwall"
primary_region = "otp"

[mounts]
  source = "postgres"
  destination = "/postgres-volume"

[env]
  PORT = "8080"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "dnnngbjci"
  NEXT_PUBLIC_CLOUDINARY_API_KEY = "717864399543867"
  NEXT_PUBLIC_CLOUDINARY_API_SECRET = "XmcvtVEHHY3G7470bFOxiQvtbaw"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
